const RatingEnum = Object.freeze({
  G: "G",
  PG: "PG",
  PG_13: "PG_13",
  R: "R",
  NC_17: "NC_17",
});

const GenreEnum = Object.freeze({
  ACTION: "Action",
  ADVENTURE: "Adventure",
  COMEDY: "Comedy",
  DRAMA: "Drama",
  HORROR: "Horror",
  ROMANCE: "Romance",
  SCIENCE_FICTION: "Science Fiction",
  THRILLER: "Thriller",
  FANTASY: "Fantasy",
  ANIMATION: "Animation",
  CRIME: "Crime",
  DOCUMENTARY: "Documentary",
  FAMILY: "Family",
  MYSTERY: "Mystery",
  MUSIC: "Music",
  WAR: "War",
  WESTERN: "Western",
  HISTORY: "History",
  BIOGRAPHY: "Biography",
  SPORT: "Sport",
  SUPERHERO: "Superhero",
  MUSICAL: "Musical",
  NOIR: "Film Noir",
  SUSPENSE: "Suspense",
  PSYCHOLOGICAL: "Psychological",
  ESPIONAGE: "Espionage",
  SATIRE: "Satire",
  EXPERIMENTAL: "Experimental",
  SUPERNATURAL: "Supernatural",
  DISASTER: "Disaster",
  SLASHER: "Slasher",
  MOCKUMENTARY: "Mockumentary",
  BLACK_COMEDY: "Black Comedy",
  INDIE: "Indie",
  ROMANTIC_COMEDY: "Romantic Comedy",
  CRIME_DRAMA: "Crime Drama",
  LEGAL_DRAMA: "Legal Drama",
  POLITICAL_DRAMA: "Political Drama",
  PARODY: "Parody",
  ZOMBIE: "Zombie",
  SURVIVAL: "Survival",
  EROTIC: "Erotic",
  NEO_NOIR: "Neo-Noir",
  REALITY: "Reality",
  ADULT: "Adult",
  FOUND_FOOTAGE: "Found Footage",
  BIOPUNK: "Biopunk",
  SLAPSTICK: "Slapstick",
  TRAGEDY: "Tragedy",
  ROAD_MOVIE: "Road Movie",
  TRAGICOMEDY: "Tragicomedy",
  FANTASY_DRAMA: "Fantasy Drama",
  SLICE_OF_LIFE: "Slice of Life",
  HISTORICAL_FICTION: "Historical Fiction",
  ANIME: "Anime",
  MILITARY: "Military",
  SWASHBUCKLER: "Swashbuckler",
  MELODRAMA: "Melodrama",
  MUSIC_VIDEO: "Music Video",
  EROTICA: "Erotica",
  GIALLO: "Giallo",
  PORNOCRIME: "Pornocrime",
});

module.exports = { RatingEnum, GenreEnum };
